envOffset: [5, 5]
surroundings:
vision:
  get_image: False
  image_type: "depth" # depth, rgb, rgbd
  frame_stack: 4
  update_freq: 4 # how many control steps do we update the image buffer
  width: 64
  height: 64

groundType:
  name: "plane" # plane, mountain range,
  staticFriction: 10.0 # [-]
  dynamicFriction: 10.0 # [-]
  restitution: 0. # [-]

# viewer cam:
viewer:
  refEnv: 0
  pos: [5, -5, 4.0] # [m]
  lookat: [4, 0, 0.2] # [m]

