learn:
  reward_params:
    tracking_sigma: 0.25
    forward_vel: 0.5
    soft_dof_pos_limit: 1.
    soft_dof_vel_limit: 1.
    soft_torque_limit: 1.
    base_height_target: 1.
  reward_scales:
    tracking_lin_vel: 2.0
    tracking_ang_vel: 1.0
    lin_vel_z: -0.8
    torques: -0.000025
    stumble: -0.0001
    feet_air_time: 0.5
    dof_vel_limits: -0.002
    torque_limits: -0.00002
    collision: -1
